baseURL = 'https://blog.1mg.org/'
languageCode = 'en-us'
title = "ijikeman's blog"
theme = 'PaperMod'

### Function Comment using Disqus
### Functions Google Analytics 4
[services]
  [services.disqus]
    shortname = 'ijikemans-site'
  [services.googleAnalytics]
    ID = 'G-HDB73CGY7H'

## PaperMod Settings
enableRobotsTXT = true

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 12

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

## 後述の検索ページにはこれが必要
[outputs]
home = ["HTML", "JSON"]

## params
[params]
env = 'production' # SEO
